# Generated by Django 3.2.1 on 2021-05-28 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20210528_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
