# Generated by Django 3.2.1 on 2021-05-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20210528_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='time',
        ),
        migrations.AddField(
            model_name='photo',
            name='topic',
            field=models.CharField(default='', max_length=200),
        ),
    ]
